# Needed YAML tag for the configuration object
--- !<tag:barectf.org,2020/3/config>

# Configuration's trace
trace:
  environment:
    domain: ust
  # Type of the trace
  type:
    # Add standard field type aliases
    $include:
      - stdint.yaml
      - stdmisc.yaml

    # Native byte order is little-endian
    native-byte-order: little-endian

    # One clock type
    clock-types:
      # The Linux FS platform requires a clock type named `default`
      # which has a 1-GHz frequency and the `uint64_t` C type.
      default:
        frequency: 1000000000
        $c-type: uint64_t

    # One data stream type
    data-stream-types:
      # Stream type named `default`
      default:
        # Default data stream type
        $is-default: true

        packet-context-field-type-extra-members:
          - cpu_id: uint32

        # Default clock type: `default`
        $default-clock-type-name: default

        # Two event record types
        event-record-types:
          
          # Event record type named `one_integer`
          func_entry:            
            payload-field-type:
              class: structure
              members:
                - addr: int32
                - call_site: int32
                - vtid: int32

          func_exit:
            payload-field-type:
              class: structure
              members:
                - addr: int32
                - call_site: int32
                - vtid: int32

